/*
 * This file is generated by jOOQ.
 */
package ch.applicator.jooq.tables;


import ch.applicator.jooq.Keys;
import ch.applicator.jooq.Public;
import ch.applicator.jooq.tables.records.JobRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Job extends TableImpl<JobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.job</code>
     */
    public static final Job JOB = new Job();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobRecord> getRecordType() {
        return JobRecord.class;
    }

    /**
     * The column <code>public.job.id</code>.
     */
    public final TableField<JobRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.job.employer</code>.
     */
    public final TableField<JobRecord, UUID> EMPLOYER = createField(DSL.name("employer"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.job.description</code>.
     */
    public final TableField<JobRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.job.position</code>.
     */
    public final TableField<JobRecord, String> POSITION = createField(DSL.name("position"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.job.original_url</code>.
     */
    public final TableField<JobRecord, String> ORIGINAL_URL = createField(DSL.name("original_url"), SQLDataType.CLOB, this, "");

    private Job(Name alias, Table<JobRecord> aliased) {
        this(alias, aliased, null);
    }

    private Job(Name alias, Table<JobRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.job</code> table reference
     */
    public Job(String alias) {
        this(DSL.name(alias), JOB);
    }

    /**
     * Create an aliased <code>public.job</code> table reference
     */
    public Job(Name alias) {
        this(alias, JOB);
    }

    /**
     * Create a <code>public.job</code> table reference
     */
    public Job() {
        this(DSL.name("job"), null);
    }

    public <O extends Record> Job(Table<O> child, ForeignKey<O, JobRecord> key) {
        super(child, key, JOB);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<JobRecord> getPrimaryKey() {
        return Keys.JOB_PKEY;
    }

    @Override
    public List<ForeignKey<JobRecord, ?>> getReferences() {
        return Arrays.asList(Keys.JOB__JOB_EMPLOYER_FKEY);
    }

    private transient Employer _employer;

    /**
     * Get the implicit join path to the <code>public.employer</code> table.
     */
    public Employer employer() {
        if (_employer == null)
            _employer = new Employer(this, Keys.JOB__JOB_EMPLOYER_FKEY);

        return _employer;
    }

    @Override
    public Job as(String alias) {
        return new Job(DSL.name(alias), this);
    }

    @Override
    public Job as(Name alias) {
        return new Job(alias, this);
    }

    @Override
    public Job as(Table<?> alias) {
        return new Job(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Job rename(String name) {
        return new Job(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Job rename(Name name) {
        return new Job(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Job rename(Table<?> name) {
        return new Job(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
