/*
 * This file is generated by jOOQ.
 */
package ch.applicator.jooq;


import ch.applicator.jooq.tables.Application;
import ch.applicator.jooq.tables.Employer;
import ch.applicator.jooq.tables.Job;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.application</code>.
     */
    public static final Application APPLICATION = Application.APPLICATION;

    /**
     * The table <code>public.employer</code>.
     */
    public static final Employer EMPLOYER = Employer.EMPLOYER;

    /**
     * The table <code>public.job</code>.
     */
    public static final Job JOB = Job.JOB;
}
