/*
 * This file is generated by jOOQ.
 */
package ch.applicator.jooq.tables.records;


import ch.applicator.jooq.tables.Employer;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployerRecord extends UpdatableRecordImpl<EmployerRecord> implements Record3<UUID, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.employer.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.employer.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.employer.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.employer.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.employer.website_url</code>.
     */
    public void setWebsiteUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.employer.website_url</code>.
     */
    public String getWebsiteUrl() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Employer.EMPLOYER.ID;
    }

    @Override
    public Field<String> field2() {
        return Employer.EMPLOYER.NAME;
    }

    @Override
    public Field<String> field3() {
        return Employer.EMPLOYER.WEBSITE_URL;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getWebsiteUrl();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getWebsiteUrl();
    }

    @Override
    public EmployerRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public EmployerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public EmployerRecord value3(String value) {
        setWebsiteUrl(value);
        return this;
    }

    @Override
    public EmployerRecord values(UUID value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployerRecord
     */
    public EmployerRecord() {
        super(Employer.EMPLOYER);
    }

    /**
     * Create a detached, initialised EmployerRecord
     */
    public EmployerRecord(UUID id, String name, String websiteUrl) {
        super(Employer.EMPLOYER);

        setId(id);
        setName(name);
        setWebsiteUrl(websiteUrl);
        resetChangedOnNotNull();
    }
}
