version: '3'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=applicator'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
volumes:
  postgres-data:
